# Form implementation generated from reading ui file 'ubuntu_sway_welcome/ui/shell_select.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_shellSelect(object):
    def setupUi(self, shellSelect):
        shellSelect.setObjectName("shellSelect")
        shellSelect.resize(400, 150)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(shellSelect.sizePolicy().hasHeightForWidth())
        shellSelect.setSizePolicy(sizePolicy)
        shellSelect.setMinimumSize(QtCore.QSize(400, 150))
        shellSelect.setMaximumSize(QtCore.QSize(400, 150))
        shellSelect.setWindowTitle("")
        self.verticalLayout = QtWidgets.QVBoxLayout(shellSelect)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(parent=shellSelect)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnBash = QtWidgets.QRadioButton(parent=self.groupBox)
        self.btnBash.setObjectName("btnBash")
        self.horizontalLayout_2.addWidget(self.btnBash)
        self.btnZSH = QtWidgets.QRadioButton(parent=self.groupBox)
        self.btnZSH.setObjectName("btnZSH")
        self.horizontalLayout_2.addWidget(self.btnZSH)
        self.btnFish = QtWidgets.QRadioButton(parent=self.groupBox)
        self.btnFish.setObjectName("btnFish")
        self.horizontalLayout_2.addWidget(self.btnFish)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=self.groupBox)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Apply|QtWidgets.QDialogButtonBox.StandardButton.Cancel)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(shellSelect)
        self.buttonBox.rejected.connect(shellSelect.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(shellSelect)

    def retranslateUi(self, shellSelect):
        _translate = QtCore.QCoreApplication.translate
        self.groupBox.setTitle(_translate("shellSelect", "Select default shell:"))
        self.btnBash.setText(_translate("shellSelect", "Bash (Default)"))
        self.btnZSH.setText(_translate("shellSelect", "ZSH"))
        self.btnFish.setText(_translate("shellSelect", "Fish"))
