# Form implementation generated from reading ui file 'ubuntu_sway_welcome/ui/warning.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WarningMessage(object):
    def setupUi(self, WarningMessage):
        WarningMessage.setObjectName("WarningMessage")
        WarningMessage.resize(640, 100)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WarningMessage.sizePolicy().hasHeightForWidth())
        WarningMessage.setSizePolicy(sizePolicy)
        WarningMessage.setMinimumSize(QtCore.QSize(640, 100))
        WarningMessage.setMaximumSize(QtCore.QSize(640, 100))
        WarningMessage.setWindowTitle("")
        self.verticalLayout = QtWidgets.QVBoxLayout(WarningMessage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=WarningMessage)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=WarningMessage)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(WarningMessage)
        self.buttonBox.accepted.connect(WarningMessage.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(WarningMessage)

    def retranslateUi(self, WarningMessage):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("WarningMessage", "Your system is already installed! If you wish to reinstall it, boot from the installation media."))
